version: '3'
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile81
    image: seo_suite
    container_name: seo_suite_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: seo_suite_webserver
    restart: unless-stopped
    tty: true
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9000
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  nosql_db:
    container_name: seo_suite_mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network
  redis:
    container_name: seo_suite_redis
    image: redis:latest
    ports:
      - "6379:6379"
  #Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
